### ISSUE TITLE
Switch to FakerPHP

### ISSUE THREAD

**Issue by pelmered** [pelmered/fake-car#15]
As fzaninotto/Faker is archived this should move to the FakerPHP fork: https://github.com/FakerPHP/Faker

The Faker announcement: https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

**Comment by mesiarm** [comment]
Any change in this issue?

**Comment by starvsion** [comment]
waiting for this to be resolved as well, i don't think anything changed in `FakerPHP` repo, they just bumped the version

**Comment by pelmered** [comment]
@mesiarm and @starvsion, this is now fixed and I have released a new version (1.6).
