### ISSUE TITLE
vehicleEnginePower returns InvalidArgumentException when I use it in seeder

### ISSUE THREAD

**Issue by JeffreyHuig** [pelmered/fake-car#31]
Maybe I made a silly error or I didn't understand the examples correctly.

Below is the code in my seeder:

`'engine_power' => $this->faker->vehicleEnginePower,`

**Comment by pelmered** [comment]
Thank you for the report. 
This is my bad. I never merged [this PR](https://github.com/pelmered/fake-car/pull/30) where this feature is included. 

I will try to fix that this weekend.
